In [ ]:
!pip3 install torch torchvision tqdm gensim

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
import torch
import numpy 
import tqdm

In [ ]:
torch.manual_seed(1)

In [ ]:
a = torch.ones(5)
print("Tensor: ")
print(a)
print("Numpy array: ")
print(a.numpy(), "\n")

Tensor: 
tensor([1., 1., 1., 1., 1.])
Numpy array: 
[1. 1. 1. 1. 1.] 



In [ ]:
rand = torch.rand(5,3)
print("Randomly initialized tensor: ", rand, "\n")

Randomly initialized tensor:  tensor([[0.7576, 0.2793, 0.4031],
        [0.7347, 0.0293, 0.7999],
        [0.3971, 0.7544, 0.5695],
        [0.4388, 0.6387, 0.5247],
        [0.6826, 0.3051, 0.4635]]) 



In [ ]:
zeros = torch.zeros(5,3, dtype=torch.long)
print("Tensor initialized with zeros: ", zeros, "\n")

Tensor initialized with zeros:  tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]) 



In [ ]:
zeros = torch.zeros(5,3, dtype=torch.long)
print("Tensor initialized with zeros: ", zeros, "\n")

Tensor initialized with zeros:  tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]) 



In [ ]:
redefined = torch.zeros(5,3, dtype=torch.double)
print("Tensor initialized with zeros: ", zeros, "\n")

Tensor initialized with zeros:  tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]) 



In [ ]:
data = torch.tensor([5.5, 3])
print("Tensor initilialized with data: ", data, "\n")

Tensor initilialized with data:  tensor([5.5000, 3.0000]) 



In [ ]:
redefined_too = torch.rand_like(redefined, dtype=torch.float)
print("Initializing randomly based on the size of redefined: ", redefined_too, "\n")

Initializing randomly based on the size of redefined:  tensor([[0.4550, 0.5725, 0.4980],
        [0.9371, 0.6556, 0.3138],
        [0.1980, 0.4162, 0.2843],
        [0.3398, 0.5239, 0.7981],
        [0.7718, 0.0112, 0.8100]]) 



In [ ]:
print(redefined_too.size(), "\n")

torch.Size([5, 3]) 



In [ ]:
x = torch.rand(5, 3)
y= torch.rand(5, 3)
print("Addition: ", x + y, "\n")
print("Addition alternative syntax: ", torch.add(x, y), "\n")

Addition:  tensor([[1.3967, 1.2089, 1.4771],
        [0.4001, 0.4698, 0.2781],
        [1.2007, 1.1880, 1.0924],
        [1.2657, 1.8914, 0.7650],
        [1.0412, 1.3104, 0.8918]]) 

Addition alternative syntax:  tensor([[1.3967, 1.2089, 1.4771],
        [0.4001, 0.4698, 0.2781],
        [1.2007, 1.1880, 1.0924],
        [1.2657, 1.8914, 0.7650],
        [1.0412, 1.3104, 0.8918]]) 



In [ ]:
result = torch.empty(5, 3)
print("Addition with tensor as argument: ", torch.add(x, y, out=result), "\n")

Addition with tensor as argument:  tensor([[1.3967, 1.2089, 1.4771],
        [0.4001, 0.4698, 0.2781],
        [1.2007, 1.1880, 1.0924],
        [1.2657, 1.8914, 0.7650],
        [1.0412, 1.3104, 0.8918]]) 



In [ ]:
y.add_(x)
print("Adding x to y: ", y)

Adding x to y:  tensor([[1.3967, 1.2089, 1.4771],
        [0.4001, 0.4698, 0.2781],
        [1.2007, 1.1880, 1.0924],
        [1.2657, 1.8914, 0.7650],
        [1.0412, 1.3104, 0.8918]])


In [ ]:
print("Adding 1: ", y.add_(1))

Adding 1:  tensor([[2.3967, 2.2089, 2.4771],
        [1.4001, 1.4698, 1.2781],
        [2.2007, 2.1880, 2.0924],
        [2.2657, 2.8914, 1.7650],
        [2.0412, 2.3104, 1.8918]])


In [ ]:
print("X: ", x, "\n")
print("Element at index one of each row of the matrix ", x[:, 1], "\n")

X:  tensor([[0.6397, 0.9743, 0.8300],
        [0.0444, 0.0246, 0.2588],
        [0.9391, 0.4167, 0.7140],
        [0.2676, 0.9906, 0.2885],
        [0.8750, 0.5059, 0.2366]]) 

Element at index one of each row of the matrix  tensor([0.9743, 0.0246, 0.4167, 0.9906, 0.5059]) 



In [ ]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)
print("Resizing: ")
print("Original")
print(x)
print("Resized view(16)", y, "\n")
print("Resized view(-1, 8)", z, "\n")

Resizing: 
Original
tensor([[ 0.4533,  1.1422,  0.2486, -1.7754],
        [-0.0255, -1.0233, -0.5962, -1.0055],
        [ 0.4285,  1.4761, -1.7869,  1.6103],
        [-0.7040, -0.1853, -0.9962, -0.8313]])
Resized view(16) tensor([ 0.4533,  1.1422,  0.2486, -1.7754, -0.0255, -1.0233, -0.5962, -1.0055,
         0.4285,  1.4761, -1.7869,  1.6103, -0.7040, -0.1853, -0.9962, -0.8313]) 

Resized view(-1, 8) tensor([[ 0.4533,  1.1422,  0.2486, -1.7754, -0.0255, -1.0233, -0.5962, -1.0055],
        [ 0.4285,  1.4761, -1.7869,  1.6103, -0.7040, -0.1853, -0.9962, -0.8313]]) 



In [ ]:
x = torch.ones(2, 2, requires_grad=True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [ ]:
y = x + 2 
print(y)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


In [ ]:
print(y.grad_fn)

In [ ]:
z = y * y * 3
out = z.mean()

print(z, out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward0>)


In [ ]:
out.backward()
print(x.grad)

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


In [ ]:
print(x.requires_grad)
print((x ** 2).requires_grad)

True
True


In [ ]:
with torch.no_grad():
    print((x ** 2).requires_grad)

False


In [ ]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

In [ ]:
torch.manual_seed(1)

In [ ]:
word_to_ix = {"hello": 0, "world": 1}

In [ ]:
embeds = nn.Embedding(2, 5) 
lookup_tensor = torch.tensor(list(word_to_ix.values()), dtype=torch.long)

In [ ]:
embeddings = embeds(lookup_tensor)
print(embeddings)

tensor([[ 0.6614,  0.2669,  0.0617,  0.6213, -0.4519],
        [-0.1661, -1.5228,  0.3817, -1.0276, -0.5631]],
       grad_fn=<EmbeddingBackward0>)


In [ ]:
import string
from random import choice
def generate_simple_language_corpus(SENTENCE_NUMBER=500, SENTENCE_LENGTH=7):
  alpha_d = dict.fromkeys(string.ascii_lowercase, 0)

  vocab_dataset = {}
  for c, l in enumerate(alpha_d, 0):
      vocab_dataset[c] = l*3

  prev_word = None
  simple_language_text =""

  for s in range(SENTENCE_NUMBER):
      sentence = []
      start_word = choice(range(0, 18))
      for w in range(0, SENTENCE_LENGTH):
          i = choice([x for x in range(start_word+w+0, start_word+w+3) if x not in [prev_word]])
          sentence.append(vocab_dataset[i])
          prev_word = i
      simple_language_text += " ".join(sentence) + "\n"

  return simple_language_text

In [ ]:
print(generate_simple_language_corpus(SENTENCE_NUMBER=20, SENTENCE_LENGTH=7))

ooo qqq sss rrr sss ttt www
rrr qqq ttt sss uuu vvv www
qqq rrr sss ttt vvv uuu www
rrr qqq ttt uuu ttt uuu www
ggg iii jjj lll mmm nnn mmm
ppp rrr sss ttt uuu ttt vvv
qqq sss ttt sss vvv uuu xxx
ggg iii jjj kkk lll kkk nnn
kkk mmm nnn mmm ooo ppp rrr
eee ggg iii jjj iii jjj lll
ggg iii kkk jjj lll nnn ooo
bbb ccc eee fff ggg hhh ggg
hhh iii jjj lll kkk lll ooo
jjj lll mmm nnn ppp qqq rrr
fff ggg hhh iii hhh kkk lll
nnn ooo qqq ppp qqq ttt sss
nnn ooo ppp qqq sss rrr uuu
fff hhh jjj kkk lll kkk lll
eee fff hhh jjj iii kkk mmm
iii jjj lll kkk nnn mmm ppp



In [129]:
training_corpus=generate_simple_language_corpus(SENTENCE_NUMBER=500, SENTENCE_LENGTH=7)
test_sentence = training_corpus.split()
trigrams = [([test_sentence[i-1], test_sentence[i + 1]], test_sentence[i ])
              for i in range(1,len(test_sentence) - 1)]
print(trigrams[:3])
vocab=set(test_sentence)
word_to_ix={word: i for i, word in enumerate(vocab)}

[(['ooo', 'qqq'], 'rrr'), (['rrr', 'rrr'], 'qqq'), (['qqq', 'ttt'], 'rrr')]


In [130]:
def train_word_embedding_model(training_corpus, EMBEDDING_DIM = 10, EPOCHS = 300, CONTEXT_SIZE = 2):
  test_sentence = training_corpus.split()


  # we should tokenize the input, but we will ignore that for now
  # build a list of tuples.  Each tuple is ([ word_i-2, word_i-1 ], target word)
  trigrams = [([test_sentence[i-1], test_sentence[i + 1]], test_sentence[i ])
              for i in range(1,len(test_sentence) - 1)]
  # print the first 3, just so you can see what they look like
  print(trigrams[:3])

  # deduplicate 
  vocab = set(test_sentence)

  # generate the word index
  word_to_ix = {word: i for i, word in enumerate(vocab)}


  class NGramLanguageModeler(nn.Module):

      def __init__(self, vocab_size, embedding_dim, context_size):
          super(NGramLanguageModeler, self).__init__()
          self.embeddings = nn.Embedding(vocab_size, embedding_dim)
          self.linear1 = nn.Linear(context_size * embedding_dim, 128)
          self.linear2 = nn.Linear(128, vocab_size)

      def forward(self, inputs):
          embeds = self.embeddings(inputs).view((1, -1))
          out = F.relu(self.linear1(embeds))
          out = self.linear2(out)
          log_probs = F.log_softmax(out, dim=1)
          return log_probs


  losses = []
  loss_function = nn.NLLLoss()
  model = NGramLanguageModeler(len(vocab), EMBEDDING_DIM, CONTEXT_SIZE)

  # Exercise: What do SGD and lr mean? What happenes if you change them?
  optimizer = optim.SGD(model.parameters(), lr=0.001)


  for epoch in tqdm.tqdm(range(EPOCHS),total=EPOCHS):
      total_loss = 0
      for context, target in trigrams:

          # Step 1. Prepare the inputs to be passed to the model (i.e, turn the words
          # into integer indices and wrap them in tensors)
          context_idxs = torch.tensor([word_to_ix[w] for w in context], dtype=torch.long)

          # Step 2. Recall that torch *accumulates* gradients. Before passing in a
          # new instance, you need to zero out the gradients from the old
          # instance
          model.zero_grad()

          # Step 3. Run the forward pass, getting log probabilities over next
          # words
          log_probs = model(context_idxs)

          # Step 4. Compute your loss function. (Again, Torch wants the target
          # word wrapped in a tensor)
          loss = loss_function(log_probs, torch.tensor([word_to_ix[target]], dtype=torch.long))

          # Step 5. Do the backward pass and update the gradient
          loss.backward()
          optimizer.step()

          # Get the Python number from a 1-element Tensor by calling tensor.item()
          total_loss += loss.item()

      #print("\t", total_loss)
      losses.append(total_loss)
  print(losses) # The loss decreased every iteration over the training data!

  return model, word_to_ix, losses

In [131]:
training_corpus = generate_simple_language_corpus(SENTENCE_NUMBER=500, SENTENCE_LENGTH=7)
model, word_to_ix, losses = train_word_embedding_model(training_corpus, EMBEDDING_DIM=5, EPOCHS=10, CONTEXT_SIZE = 2)

[(['qqq', 'ttt'], 'rrr'), (['rrr', 'sss'], 'ttt'), (['ttt', 'vvv'], 'sss')]


100%|██████████| 10/10 [00:10<00:00,  1.06s/it]

[10679.036934614182, 9506.460078239441, 8737.1942730546, 8158.953963577747, 7705.553641736507, 7335.861798495054, 7025.217261195183, 6758.608599573374, 6524.383681803942, 6315.530577838421]


In [133]:
def get_word_embedding_for_word(word_to_test, word_to_ix):
  word_to_test_ix = word_to_ix[word_to_test]
  word_to_test_torch = torch.tensor([word_to_test_ix], dtype=torch.long)
  
  embedding_of_word_to_test = model.embeddings(word_to_test_torch)
  return embedding_of_word_to_test

def most_similar(word_to_test, word_to_ix):
  test_embedding = get_word_embedding_for_word(word_to_test, word_to_ix)

  # get embeddings for all other possible words like aaa bbb ccc
  cos = torch.nn.CosineSimilarity()
  results = {}
  for c in string.ascii_lowercase:
    c_embedding = get_word_embedding_for_word(c+c+c, word_to_ix)

    cosine_similarity = cos(test_embedding, c_embedding)
    results[c+c+c] = cosine_similarity.item()
  sorted_results =  dict(sorted(results.items(), key=lambda item: -item[1]))
  return sorted_results

sims = most_similar("eee", word_to_ix)

for k,v in sims.items():
  print("{}: {}".format(k,v))

eee: 1.0000001192092896
vvv: 0.6627718806266785
iii: 0.4294011890888214
ppp: 0.3059576749801636
hhh: 0.28882744908332825
rrr: 0.27251893281936646
bbb: 0.23518235981464386
xxx: 0.21666806936264038
yyy: 0.18408668041229248
fff: 0.1359090805053711
ccc: 0.024255692958831787
sss: 0.013381972908973694
ttt: 0.009966760873794556
aaa: -0.05397161841392517
ggg: -0.09005162119865417
kkk: -0.1759956181049347
zzz: -0.25549647212028503
nnn: -0.27761080861091614
mmm: -0.34966522455215454
www: -0.41192978620529175
ddd: -0.4676986038684845
uuu: -0.5592547655105591
lll: -0.6600804924964905
jjj: -0.6975461840629578
qqq: -0.7777866721153259
ooo: -0.8772643208503723


In [134]:
import gensim 
from sklearn.decomposition import PCA 
from matplotlib import pyplot 

import warnings 
warnings.filterwarnings('ignore') 

training_corpus =  generate_simple_language_corpus(SENTENCE_NUMBER=3000, SENTENCE_LENGTH=7)

# we have to convert the corpus to a different form for gensim
training_corpus_gensim = [w.split(" ") for w in training_corpus.split("\n")]


model = gensim.models.Word2Vec(training_corpus_gensim, window=2) 

model.most_similar('ccc')

[('ddd', 0.9975908994674683),
 ('bbb', 0.9941346645355225),
 ('eee', 0.9881815910339355),
 ('iii', 0.987351655960083),
 ('fff', 0.9868288040161133),
 ('aaa', 0.986311674118042),
 ('jjj', 0.9852902889251709),
 ('ggg', 0.9835245609283447),
 ('kkk', 0.9815967082977295),
 ('hhh', 0.981393575668335)]

In [135]:
!wget https://github.com/dgromann/SemanticComputing/raw/master/tutorial6/word2vec_embeddings.bin
!wget https://raw.githubusercontent.com/dgromann/SemComp_WS2018/master/Tutorial6/analogy.txt


--2022-10-22 14:50:11--  https://github.com/dgromann/SemanticComputing/raw/master/tutorial6/word2vec_embeddings.bin
Resolving github.com (github.com)... 192.30.255.113
Connecting to github.com (github.com)|192.30.255.113|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://raw.githubusercontent.com/dgromann/SemanticComputing/master/tutorial6/word2vec_embeddings.bin [following]
--2022-10-22 14:50:11--  https://raw.githubusercontent.com/dgromann/SemanticComputing/master/tutorial6/word2vec_embeddings.bin
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.110.133, 185.199.108.133, 185.199.111.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.110.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 96769269 (92M) [application/octet-stream]
Saving to: ‘word2vec_embeddings.bin’

word2vec_embeddings 100%[===================>]  92.29M   320MB/s    in 0.3s    

2022-10-22 14:50:1

In [136]:
import gensim
from sklearn.decomposition import PCA
from matplotlib import pyplot

import warnings
warnings.filterwarnings('ignore')

In [137]:
# Let's load the model
model = gensim.models.KeyedVectors.load_word2vec_format("word2vec_embeddings.bin", binary=True)

# Print the length fo the whole vocabulary 
print(len(model.wv.vocab))

# Print the embedding of a specific word 
print(model["good"])

# Get the 10 most similar words of "good"
print(model.most_similar("good", topn=10))

# Check whether our embeddings are good at the analogy task
print(model.most_similar(positive=['women', 'king'], negative=['man'], topn=1))

80000
[ 0.04052734  0.0625     -0.01745605  0.07861328  0.03271484 -0.01263428
  0.00964355  0.12353516 -0.02148438  0.15234375 -0.05834961 -0.10644531
  0.02124023  0.13574219 -0.13183594  0.17675781  0.27148438  0.13769531
 -0.17382812 -0.14160156 -0.03076172  0.19628906 -0.03295898  0.125
  0.25390625  0.12695312 -0.15234375  0.03198242  0.01135254 -0.01361084
 -0.12890625  0.01019287  0.23925781 -0.08447266  0.140625    0.13085938
 -0.04516602  0.06494141  0.02539062  0.05615234  0.24609375 -0.20507812
  0.23632812 -0.00860596 -0.02294922  0.05078125  0.10644531 -0.03564453
  0.08740234 -0.05712891  0.08496094  0.23535156 -0.10107422 -0.03564453
 -0.04736328  0.04736328 -0.14550781 -0.10986328  0.14746094 -0.23242188
 -0.07275391  0.19628906 -0.37890625 -0.07226562  0.04833984  0.11914062
  0.06103516 -0.12109375 -0.27929688  0.05200195  0.04907227 -0.02709961
  0.1328125   0.03369141 -0.32226562  0.04223633 -0.08789062  0.15429688
  0.09472656  0.10351562 -0.02856445  0.00128174 -